# k8s/deployment.yaml
#
# Kubernetes Deployment for the Deno container detector.
# Adjust image: tag to your registry/image if you push it.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-sense-app
  labels:
    app: infra-sense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-sense
  template:
    metadata:
      labels:
        app: infra-sense
    spec:
      containers:
        - name: infra-sense
          image: infra-sense:latest
          imagePullPolicy: IfNotPresent
          command:
            [
              "deno",
              "run",
              "detect",
            ]
      restartPolicy: OnFailure
