FROM denoland/deno:1.36.4-alpine AS builder
WORKDIR /app
COPY deno.json deno.lock ./
COPY src ./src
COPY main.ts ./
RUN deno cache src/mod.ts

FROM gcr.io/distroless/static:nonroot
COPY --from=builder /deno /deno
COPY --from=builder /app /app
USER nonroot:nonroot
ENTRYPOINT ["/deno", "run", "detect"]
